### ISSUE TITLE
[MacOS] Problems using GUI / CLI

### ISSUE THREAD

**Issue by apfelbasti** [laggykiller/sticker-convert#7]
I have problems using GUI and CLI. I downloaded Release v1.8.0 for MacOS and tried to Download Sticker (from Signal and Export to WhatsApp). The Terminal says:
```
sticker-convert-macos % ./sticker-convert 
Launching GUI...
Exception in thread Thread-1 (start_process):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "gui.py", line 731, in start_process
  File "downloaders/download_signal.py", line 31, in download_stickers_signal
  File "anyio/_core/_eventloop.py", line 53, in run
  File "anyio/_backends/_asyncio.py", line 160, in run
  File "asyncio/runners.py", line 190, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 653, in run_until_complete
  File "anyio/_backends/_asyncio.py", line 155, in wrapper
  File "downloaders/download_signal.py", line 21, in download_stickers_signal_async
  File "anyio/_backends/_asyncio.py", line 436, in __aexit__
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "downloaders/download_signal.py", line 25, in download_stickers_signal_async
AttributeError: 'int' object has no attribute 'zfill'
----------------------------
Traceback (most recent call last):
  File "anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
  File "downloaders/download_signal.py", line 11, in save_sticker
AttributeError: 'int' object has no attribute 'zfill'
```
The CLI does say this:
```
sticker-convert-macos % ./sticker-convert --download-signal (here is the URL) --export-wastickers
[1] 65161
zsh: command not found: --export-wastickers
sticker-convert-macos % Loaded credentials from creds.json
Traceback (most recent call last):
  File "main.py", line 42, in <module>
  File "main.py", line 38, in main
  File "cli.py", line 221, in cli
AttributeError: 'Namespace' object has no attribute 'duration_min'
[65161] Failed to execute script 'main' due to unhandled exception!

[1]  + exit 1     ./sticker-convert --download-signal 
```
Do I forget something?

**Comment by laggykiller** [comment]
Thank you for your bug report. v1.8.1 should fix this

**Comment by apfelbasti** [comment]
After update to v1.8.1 (the last call repeats every time...) - the web-Files are not in the Download-Folder.
```
sticker-convert-macos % ./sticker-convert 
Launching GUI...
Downloaded 000.webp
Downloaded 001.webp
Downloaded 002.webp
Downloaded 003.webp
Downloaded 004.webp
Downloaded 005.webp
Downloaded 006.webp
Downloaded 007.webp
Downloaded 008.webp
Downloaded 009.webp
Downloaded 010.webp
Downloaded 011.webp
Downloaded 012.webp
Downloaded 013.webp
Downloaded 014.webp
Downloaded 015.webp
Downloaded 016.webp
Downloaded 017.webp
Downloaded 018.webp
Downloaded 019.webp
Downloaded 020.webp
Downloaded 021.webp
Downloaded 022.webp
Downloaded 023.webp
Downloaded 024.webp
Downloaded 025.webp
Downloaded 026.webp
Downloaded 027.webp
Downloaded 028.webp
Downloaded 029.webp
Downloaded 030.webp
Downloaded 031.webp
Downloaded 032.webp
Downloaded 033.webp
Downloaded 034.webp
Downloaded 035.webp
Downloaded 036.webp
Downloaded 037.webp
Downloaded 038.webp
Downloaded 039.webp
Downloaded 040.webp
Downloaded 041.webp
Downloaded 042.webp
Exception in thread Thread-1 (start_process):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "gui.py", line 731, in start_process
  File "downloaders/download_signal.py", line 31, in download_stickers_signal
  File "anyio/_core/_eventloop.py", line 53, in run
  File "anyio/_backends/_asyncio.py", line 160, in run
  File "asyncio/runners.py", line 190, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 653, in run_until_complete
  File "anyio/_backends/_asyncio.py", line 155, in wrapper
  File "downloaders/download_signal.py", line 21, in download_stickers_signal_async
  File "anyio/_backends/_asyncio.py", line 436, in __aexit__
anyio._backends._asyncio.ExceptionGroup: 43 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
  File "downloaders/download_signal.py", line 11, in save_sticker
AttributeError: 'int' object has no attribute 'zfill'
----------------------------
Traceback (most recent call last):
  File "anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
  File "downloaders/download_signal.py", line 11, in save_sticker
AttributeError: 'int' object has no attribute 'zfill'
----------------------------
```
CLI:
```
sticker-convert-macos % ./sticker-convert --download-signal (here is the URL) --export-wastickers
[1] 68772
zsh: command not found: --export-wastickers
sticker-convert-macos % Loaded credentials from creds.json
Traceback (most recent call last):
  File "main.py", line 42, in <module>
  File "main.py", line 38, in main
  File "cli.py", line 230, in cli
  File "downloaders/download_signal.py", line 31, in download_stickers_signal
  File "anyio/_core/_eventloop.py", line 53, in run
  File "anyio/_backends/_asyncio.py", line 160, in run
  File "asyncio/runners.py", line 190, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 653, in run_until_complete
  File "anyio/_backends/_asyncio.py", line 155, in wrapper
  File "downloaders/download_signal.py", line 15, in download_stickers_signal_async
IndexError: list index out of range
[68772] Failed to execute script 'main' due to unhandled exception!

[1]  + exit 1     ./sticker-convert --download-signal 
```

**Comment by laggykiller** [comment]
Seems like I missed one of the zfill'ing on int... v1.9.0 should fix this problem.

For CLI, I think you did not wrap the URL between quotes.

Also please enjoy the new GUI!

**Comment by apfelbasti** [comment]
Release v1.9.1 does work. Thank you! 
An option to remove the stickers_input/output folder would be nice.
I'll try the CLI later, there I had some problems but GUI does work for Signal to WhatsApp.

**Comment by laggykiller** [comment]
What problem you got in CLI? Can you post the output?

**Comment by laggykiller** [comment]
No reply received, closing.

If you still encounter problem, please feel free to open another issue.
